In [ ]:
pip install openai num2words matplotlib plotly scipy scikit-learn pandas tiktoken

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.3/143.3 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.2/325.2 kB 17.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.9 MB/s eta 0:00:00
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=034c2d042332c7c3e2c58ea5b4310d112062fe494cc631b14c81959f5c5855c3
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt


# New Section

In [ ]:
import os
import re
import requests
import sys
import os
import pandas as pd
import numpy as np
import tiktoken
from openai import AzureOpenAI

In [ ]:
df=pd.read_csv('/content/df_concat.csv')

In [ ]:
df_copy = df.copy(deep=True)

In [ ]:
df.columns

Index(['Unnamed: 0', 'type', 'title', 'director', 'cast', 'country',
       'date_added', 'release_year', 'rating', 'duration', 'listed_in',
       'description', 'month_added', 'month_name_added', 'year_added',
       'type_of_movie'],
      dtype='object')

In [ ]:
df.head()

Unnamed: 0     type                                             title  \
0           0    Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1           1    Movie                            Ernest Saves Christmas   
2           2    Movie                      Ice Age: A Mammoth Christmas   
3           3    Movie                        The Queen Family Singalong   
4           4  TV Show                             The Beatles: Get Back   

                            director  \
0  Alonso Ramirez Ramos, Dave Wasson   
1                        John Cherry   
2                       Karen Disher   
3                    Hamish Hamilton   
4                            No Data   

                                                cast        country  \
0  Chris Diamantopoulos, Tony Anselmo, Tress MacN...  United States   
1           Jim Varney, Noelle Parker, Douglas Seale  United States   
2  Raymond Albert Romano, John Leguizamo, Denis L...  United States   
3  Darren Criss, Adam Lambert, Derek Hough, Alexa...  United States   
4  John Lennon, Paul McCartney, George Harrison, ...  United States   

   date_added  release_year rating  duration                      listed_in  \
0  2021-11-26          2016   TV-G    23 min              Animation, Family   
1  2021-11-26          1988     PG    91 min                         Comedy   
2  2021-11-26          2011   TV-G    23 min      Animation, Comedy, Family   
3  2021-11-26          2021  TV-PG    41 min                        Musical   
4  2021-11-25          2021    NaN  1 Season  Docuseries, Historical, Music   

                                         description  month_added  \
0   Join Mickey and the gang as they duck the halls!           11   
1  Santa Claus passes his magic bag to a new St. ...           11   
2          Sid the Sloth is on Santa's naughty list.           11   
3               This is real life, not just fantasy!           11   
4  A three-part documentary from Peter Jackson ca...           11   

  month_name_added  year_added type_of_movie  
0         November        2021     Animation  
1         November        2021        Comedy  
2         November        2021     Animation  
3         November        2021       Musical  
4         November        2021    Docuseries

In [ ]:
df.replace('No Data', 'no_data', inplace=True)

In [ ]:
df.drop(columns=['Unnamed: 0','date_added','duration', 'month_added', 'month_name_added', 'year_added', 'type_of_movie'],inplace=True)

In [ ]:
df.head()

type                                             title  \
0    Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1    Movie                            Ernest Saves Christmas   
2    Movie                      Ice Age: A Mammoth Christmas   
3    Movie                        The Queen Family Singalong   
4  TV Show                             The Beatles: Get Back   

                            director  \
0  Alonso Ramirez Ramos, Dave Wasson   
1                        John Cherry   
2                       Karen Disher   
3                    Hamish Hamilton   
4                            no_data   

                                                cast        country  \
0  Chris Diamantopoulos, Tony Anselmo, Tress MacN...  United States   
1           Jim Varney, Noelle Parker, Douglas Seale  United States   
2  Raymond Albert Romano, John Leguizamo, Denis L...  United States   
3  Darren Criss, Adam Lambert, Derek Hough, Alexa...  United States   
4  John Lennon, Paul McCartney, George Harrison, ...  United States   

   release_year rating                      listed_in  \
0          2016   TV-G              Animation, Family   
1          1988     PG                         Comedy   
2          2011   TV-G      Animation, Comedy, Family   
3          2021  TV-PG                        Musical   
4          2021    NaN  Docuseries, Historical, Music   

                                         description  
0   Join Mickey and the gang as they duck the halls!  
1  Santa Claus passes his magic bag to a new St. ...  
2          Sid the Sloth is on Santa's naughty list.  
3               This is real life, not just fantasy!  
4  A three-part documentary from Peter Jackson ca...

In [ ]:
def create_textual_representation(row):
    txt= f"""Type: {row['type']}
Director: {row['director']}
Cast: {row['cast']}
Release Year: {row['release_year']}
Country: {row['country']}
Genre: {row['listed_in']}

Description: {row['cleaned_description']}"""

    return txt

In [ ]:
def clean_text(text):
    # Remove punctuation
    punctuation = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
    text = ''.join([char for char in text if char not in punctuation])

    # Convert to lowercase
    text = text.lower()

    # Remove extra whitespace
    text = ' '.join(text.split())

    return text

In [ ]:
def trim_cast(cast_str):
    """Trims the cast string to only the first 3 actors and returns them as a list with spaces replaced by underscores."""
    if isinstance(cast_str, str):
        actors = cast_str.split(',')
        return [actor.strip().replace(' ', '_') for actor in actors[:3]]
    return []

In [ ]:
df['cast'] = df['cast'].apply(lambda x: ', '.join(trim_cast(x)))
df['director'] = df['director'].apply(lambda x: ', '.join(trim_cast(x)))

In [ ]:
df['cleaned_description'] = df['description'].apply(clean_text)

In [ ]:
df['textual_representation']=df.apply(create_textual_representation, axis=1)

In [ ]:
print(df['textual_representation'].values[0])

Type: Movie
Director: Alonso_Ramirez_Ramos, Dave_Wasson
Cast: Chris_Diamantopoulos, Tony_Anselmo, Tress_MacNeille
Release Year: 2016
Country: United States
Genre: Animation, Family

Description: join mickey and the gang as they duck the halls


In [ ]:
tokenizer = tiktoken.get_encoding("cl100k_base")
df['n_tokens'] = df["textual_representation"].apply(lambda x: len(tokenizer.encode(x)))

In [ ]:
total_tokens = df['n_tokens'].sum()
print(f"Total number of tokens: {total_tokens}")
print(f"Total cost of tokens: {total_tokens*0.0001/1000} $")

Total number of tokens: 786295
Total cost of tokens: 0.0786295 $


In [ ]:
df.head()

type                                             title  \
0    Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1    Movie                            Ernest Saves Christmas   
2    Movie                      Ice Age: A Mammoth Christmas   
3    Movie                        The Queen Family Singalong   
4  TV Show                             The Beatles: Get Back   

                            director  \
0  Alonso_Ramirez_Ramos, Dave_Wasson   
1                        John_Cherry   
2                       Karen_Disher   
3                    Hamish_Hamilton   
4                            no_data   

                                                cast        country  \
0  Chris_Diamantopoulos, Tony_Anselmo, Tress_MacN...  United States   
1           Jim_Varney, Noelle_Parker, Douglas_Seale  United States   
2  Raymond_Albert_Romano, John_Leguizamo, Denis_L...  United States   
3            Darren_Criss, Adam_Lambert, Derek_Hough  United States   
4       John_Lennon, Paul_McCartney, George_Harrison  United States   

   release_year rating                      listed_in  \
0          2016   TV-G              Animation, Family   
1          1988     PG                         Comedy   
2          2011   TV-G      Animation, Comedy, Family   
3          2021  TV-PG                        Musical   
4          2021    NaN  Docuseries, Historical, Music   

                                         description  \
0   Join Mickey and the gang as they duck the halls!   
1  Santa Claus passes his magic bag to a new St. ...   
2          Sid the Sloth is on Santa's naughty list.   
3               This is real life, not just fantasy!   
4  A three-part documentary from Peter Jackson ca...   

                                 cleaned_description  \
0    join mickey and the gang as they duck the halls   
1   santa claus passes his magic bag to a new st nic   
2            sid the sloth is on santas naughty list   
3                 this is real life not just fantasy   
4  a threepart documentary from peter jackson cap...   

                              textual_representation  n_tokens  
0  Type: Movie\nDirector: Alonso_Ramirez_Ramos, D...        70  
1  Type: Movie\nDirector: John_Cherry\nCast: Jim_...        55  
2  Type: Movie\nDirector: Karen_Disher\nCast: Ray...        63  
3  Type: Movie\nDirector: Hamish_Hamilton\nCast: ...        53  
4  Type: TV Show\nDirector: no_data\nCast: John_L...        70

In [ ]:
df.shape

(10130, 12)

In [ ]:
client = AzureOpenAI(
    azure_endpoint="https://openainew2211.openai.azure.com/",
    api_key="e1ce1acd133b4d69a78cad5c666223de",
    api_version="2024-02-01"
)

In [ ]:
def generate_embeddings(text, model="text-embedding-ada-002"):
    return client.embeddings.create(input = [text], model=model).data[0].embedding

In [ ]:
df['ada_v2'] = df["textual_representation"].apply(lambda x : generate_embeddings (x, model = 'text-embedding-ada-002'))

In [ ]:
df.head()

type                                             title  \
0    Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1    Movie                            Ernest Saves Christmas   
2    Movie                      Ice Age: A Mammoth Christmas   
3    Movie                        The Queen Family Singalong   
4  TV Show                             The Beatles: Get Back   

                            director  \
0  Alonso_Ramirez_Ramos, Dave_Wasson   
1                        John_Cherry   
2                       Karen_Disher   
3                    Hamish_Hamilton   
4                            no_data   

                                                cast        country  \
0  Chris_Diamantopoulos, Tony_Anselmo, Tress_MacN...  United States   
1           Jim_Varney, Noelle_Parker, Douglas_Seale  United States   
2  Raymond_Albert_Romano, John_Leguizamo, Denis_L...  United States   
3            Darren_Criss, Adam_Lambert, Derek_Hough  United States   
4       John_Lennon, Paul_McCartney, George_Harrison  United States   

   release_year rating                      listed_in  \
0          2016   TV-G              Animation, Family   
1          1988     PG                         Comedy   
2          2011   TV-G      Animation, Comedy, Family   
3          2021  TV-PG                        Musical   
4          2021    NaN  Docuseries, Historical, Music   

                                         description  \
0   Join Mickey and the gang as they duck the halls!   
1  Santa Claus passes his magic bag to a new St. ...   
2          Sid the Sloth is on Santa's naughty list.   
3               This is real life, not just fantasy!   
4  A three-part documentary from Peter Jackson ca...   

                                 cleaned_description  \
0    join mickey and the gang as they duck the halls   
1   santa claus passes his magic bag to a new st nic   
2            sid the sloth is on santas naughty list   
3                 this is real life not just fantasy   
4  a threepart documentary from peter jackson cap...   

                              textual_representation  n_tokens  \
0  Type: Movie\nDirector: Alonso_Ramirez_Ramos, D...        70   
1  Type: Movie\nDirector: John_Cherry\nCast: Jim_...        55   
2  Type: Movie\nDirector: Karen_Disher\nCast: Ray...        63   
3  Type: Movie\nDirector: Hamish_Hamilton\nCast: ...        53   
4  Type: TV Show\nDirector: no_data\nCast: John_L...        70   

                                              ada_v2  
0  [-0.004417451564222574, -0.02741820551455021, ...  
1  [0.0017536545637995005, -0.0326634906232357, -...  
2  [-0.00391661049798131, -0.015575433149933815, ...  
3  [-0.0018677887273952365, -0.02954970672726631,...  
4  [-0.003931119572371244, -0.02340295910835266, ...

In [ ]:
df.to_csv('df_with_embeddings.csv', index=False)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Extract the embeddings as a NumPy array
embeddings_matrix = np.stack(df['ada_v2'].values)

# Calculate the cosine similarity matrix
cosine_sim_matrix = cosine_similarity(embeddings_matrix)

# You now have a cosine similarity matrix where cosine_sim_matrix[i][j] represents the
# cosine similarity between the embedding of item i and item j.

print(cosine_sim_matrix)

[[1.         0.80712338 0.83416796 ... 0.82279704 0.84654992 0.81210712]
 [0.80712338 1.         0.84250461 ... 0.80016005 0.83202288 0.78629445]
 [0.83416796 0.84250461 1.         ... 0.80564048 0.83435901 0.79409077]
 ...
 [0.82279704 0.80016005 0.80564048 ... 1.         0.83621743 0.82755757]
 [0.84654992 0.83202288 0.83435901 ... 0.83621743 1.         0.81765859]
 [0.81210712 0.78629445 0.79409077 ... 0.82755757 0.81765859 1.        ]]


In [ ]:
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=df['title'], columns=df['title'])

In [ ]:
cosine_sim_df.head()

title                                             Duck the Halls: A Mickey Mouse Christmas Special  \
title                                                                                                
Duck the Halls: A Mickey Mouse Christmas Special                                          1.000000   
Ernest Saves Christmas                                                                    0.807123   
Ice Age: A Mammoth Christmas                                                              0.834168   
The Queen Family Singalong                                                                0.810547   
The Beatles: Get Back                                                                     0.784283   

title                                             Ernest Saves Christmas  \
title                                                                      
Duck the Halls: A Mickey Mouse Christmas Special                0.807123   
Ernest Saves Christmas                                          1.000000   
Ice Age: A Mammoth Christmas                                    0.842505   
The Queen Family Singalong                                      0.780857   
The Beatles: Get Back                                           0.769345   

title                                             Ice Age: A Mammoth Christmas  \
title                                                                            
Duck the Halls: A Mickey Mouse Christmas Special                      0.834168   
Ernest Saves Christmas                                                0.842505   
Ice Age: A Mammoth Christmas                                          1.000000   
The Queen Family Singalong                                            0.786400   
The Beatles: Get Back                                                 0.755399   

title                                             The Queen Family Singalong  \
title                                                                          
Duck the Halls: A Mickey Mouse Christmas Special                    0.810547   
Ernest Saves Christmas                                              0.780857   
Ice Age: A Mammoth Christmas                                        0.786400   
The Queen Family Singalong                                          1.000000   
The Beatles: Get Back                                               0.807295   

title                                             The Beatles: Get Back  \
title                                                                     
Duck the Halls: A Mickey Mouse Christmas Special               0.784283   
Ernest Saves Christmas                                         0.769345   
Ice Age: A Mammoth Christmas                                   0.755399   
The Queen Family Singalong                                     0.807295   
The Beatles: Get Back                                          1.000000   

title                                             Becoming Cousteau   Hawkeye  \
title                                                                           
Duck the Halls: A Mickey Mouse Christmas Special           0.800482  0.813161   
Ernest Saves Christmas                                     0.761354  0.790955   
Ice Age: A Mammoth Christmas                               0.772180  0.774309   
The Queen Family Singalong                                 0.785453  0.793144   
The Beatles: Get Back                                      0.783441  0.804394   

title                                             Port Protection Alaska  \
title                                                                      
Duck the Halls: A Mickey Mouse Christmas Special                0.773711   
Ernest Saves Christmas                                          0.756960   
Ice Age: A Mammoth Christmas                                    0.746722   
The Queen Family Singalong                                      0.769655   
The Beatles: Get Back                                           0.

In [ ]:
def get_recommendations(title, cosine_sim_df, top_n=10):
  """
  Recommends similar movies based on cosine similarity.

  Args:
      title: The title of the movie for which to find recommendations.
      cosine_sim_df: A DataFrame containing the cosine similarity matrix.
      top_n: The number of top similar movies to return.

  Returns:
      A list of recommended movie titles.
  """
  try:
    # Get the row corresponding to the given title
    similarity_scores = cosine_sim_df.loc[title]

    # Sort the similarity scores in descending order
    similarity_scores = similarity_scores.sort_values(ascending=False)

    # Get the top N similar movies (excluding the movie itself)
    top_similar_movies = similarity_scores[1:top_n + 1].index.tolist()

    return top_similar_movies
  except KeyError:
    print(f"Movie '{title}' not found in the dataset.")
    return []

In [ ]:
movie_title = "The Matrix"
recommended_movies = get_recommendations(movie_title, cosine_sim_df, top_n=5)

print(f"Top 5 recommendations for '{movie_title}':")
for movie in recommended_movies:
  print(movie)

Top 5 recommendations for 'The Matrix':
The Matrix Reloaded
The Matrix Revolutions
Transcendence
Jupiter Ascending
Swordfish


In [ ]:
import pickle

with open('cosine_sim_df.pickle', 'wb') as f:
    pickle.dump(cosine_sim_df, f)

In [ ]:
# Calculate the memory usage in bytes
memory_usage_bytes = cosine_sim_df.memory_usage(deep=True).sum()

# Convert bytes to megabytes
memory_usage_mb = memory_usage_bytes / (1024 ** 2)

print(f"Memory usage of the DataFrame: {memory_usage_mb:.2f} MB")

In [ ]:
cosine_sim_df1 = cosine_sim_df.astype(np.float32)

# Calculate the new memory usage in bytes
new_memory_usage_bytes = cosine_sim_df1.memory_usage(deep=True).sum()

# Convert bytes to megabytes
new_memory_usage_mb = new_memory_usage_bytes / (1024 ** 2)

print(f"New memory usage of the DataFrame: {new_memory_usage_mb:.2f} MB")

In [ ]:
with open('cosine_sim_df.pickle', 'wb') as f:
    pickle.dump(cosine_sim_df1, f)